In [1]:
import numpy as np
import pandas as pd
import random

In [32]:
A = np.matrix(np.random.randn(4,4))
A

matrix([[ 0.44574212,  1.07183437,  0.07430976,  1.52797153],
        [-3.35167271,  0.73932409,  1.70205541, -0.80700227],
        [-1.00449046,  0.03663619, -0.17543934,  0.85323826],
        [ 0.32089497,  1.22576566, -1.13890125, -0.22817407]])

In [33]:
U, sigma, Vtrans = np.linalg.svd(A)

In [34]:
sigma

array([ 4.03505247,  2.07006077,  1.54263019,  0.89081625])

In [35]:
A[0] = A[1] + A[2]
A[-1] = A[1]
A

matrix([[-4.35616317,  0.77596028,  1.52661606,  0.046236  ],
        [-3.35167271,  0.73932409,  1.70205541, -0.80700227],
        [-1.00449046,  0.03663619, -0.17543934,  0.85323826],
        [-3.35167271,  0.73932409,  1.70205541, -0.80700227]])

In [74]:
U, sigma, Vtrans = np.linalg.svd(A)
sigma = np.around(sigma, decimals=4)
sigma

array([ 7.2318,  1.4279,  0.    ,  0.    ])

In [75]:
U[:,:2]

matrix([[-0.64157387,  0.43403107],
        [-0.53736561, -0.33352391],
        [-0.10420826,  0.76755497],
        [-0.53736561, -0.33352391]])

In [76]:
Vtrans[:2,]

matrix([[ 0.89903809, -0.17924116, -0.38585468,  0.10353395],
        [-0.29832858, -0.08981905, -0.4253865 ,  0.84969343]])

In [77]:
np.diag(sigma[:2])

array([[ 7.2318,  0.    ],
       [ 0.    ,  1.4279]])

In [78]:
A

matrix([[-4.35616317,  0.77596028,  1.52661606,  0.046236  ],
        [-3.35167271,  0.73932409,  1.70205541, -0.80700227],
        [-1.00449046,  0.03663619, -0.17543934,  0.85323826],
        [-3.35167271,  0.73932409,  1.70205541, -0.80700227]])

In [79]:
np.matrix([[-0.64157387,  0.43403107],
        [-0.53736561, -0.33352391],
        [-0.10420826,  0.76755497],
        [-0.53736561, -0.33352391]]) * \

np.array([[ 7.2318,  0.    ],
       [ 0.    ,  1.4279]]) * \

np.matrix([[ 0.89903809, -0.17924116, -0.38585468,  0.10353395],
        [-0.29832858, -0.08981905, -0.4253865 ,  0.84969343]])


matrix([[-4.35618754,  0.77596567,  1.5266285 ,  0.04623004],
        [-3.35169482,  0.73932808,  1.70206338, -0.80700239],
        [-1.00449272,  0.03663758, -0.17543487,  0.85323242],
        [-3.35169482,  0.73932808,  1.70206338, -0.80700239]])

In [6]:
A = np.matrix([[1,0,0,0,2],
               [0,3,2,0,0], 
               [0,0,0,0,0],
               [0,2,0,1,0]])

In [7]:
A

matrix([[1, 0, 0, 0, 2],
        [0, 3, 2, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 2, 0, 1, 0]])